version: "3.8"
services:
  backend:
    image: "carant06/springboot-react-fullstack:15.8.2021.17.39.5"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
