version: "3.8"
services:
  backend:
    image: "carant06/springboot-react-fullstack:8.8.2021.1.7.17"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
